Repository AaronSosaRamos/ai-writing-services-frontend, pull requests merged in 2024-09, with the labels that each got.

#4 new navbar imp.
  src/components/Navbar.tsx
Labels: documentation, enhancement, good first issue

#5 new main screen imp.
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/MainScreen.tsx
Labels: documentation, enhancement, help wanted, good first issue

#6 new main screen imp.
  src/App.tsx
  src/pages/MainScreen.tsx
Labels: documentation, enhancement, help wanted

#7 patch for navbar bug
  src/components/Navbar.tsx
Labels: bug, documentation, enhancement

#8 new mocked screens for ai writing enhancement
  src/App.tsx
  src/pages/AIWritingEnhancementForm.tsx
  src/responses/WritingEnhancementResponse.tsx
Labels: documentation, enhancement, help wanted, good first issue

#9 new addition of connectors feature
  src/App.tsx
  src/pages/AIAdditionOfConnectorsForm.tsx
  src/pages/AIWritingEnhancementForm.tsx
  src/responses/AdditionOfConnectorsResponse.tsx
Labels: documentation, enhancement, help wanted, good first issue

#10 new ai textual tone shift imp.
  src/App.tsx
  src/pages/AIAdditionOfConnectorsForm.tsx
  src/pages/AITextualToneShiftForm.tsx
  src/pages/SpellingCheckForm.tsx
  src/responses/TextualToneShiftResponse.tsx
Labels: documentation, enhancement, good first issue

#11 new ai plagiarism check mocked screens imp.
  src/App.tsx
  src/pages/AIPlagiarismCheckForm.tsx
  src/responses/PlagiarismCheckResponse.tsx
Labels: documentation, enhancement, help wanted

#12 integration/ai-writing-enhancement
  src/components/Footer.tsx
  src/pages/AIWritingEnhancementForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#13 integration/ai-addition-of-connectors
  src/pages/AIAdditionOfConnectorsForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#14 integration/ai-textual-tone-shift
  src/pages/AITextualToneShiftForm.tsx
Labels: documentation, enhancement, help wanted, good first issue
